#!/bin/bash
#
# https://github.com/grycap/docker-rocci-server
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# --------------------------------------------------------------
# Set your configuration variables
# --------------------------------------------------------------
HOSTNAME=occiserver.localdomain
HOSTCERT_PATH=/etc/grid-security/hostcert.pem
HOSTKEY_PATH=/etc/grid-security/hostkey.pem
ONEAUTH_PATH=/var/lib/one/.one/
DOCKERIMAGE=ubuntu:rocci1.1
DOCKERHOST=$(ip -4 -o addr show docker0 | sed 's/.* \([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\)[^0-9].*/\1/')

docker run -p 11443:11443 --restart=always --name rocci -h $HOSTNAME -v $HOSTCERT_PATH:/etc/grid-security/hostcert.pem -v $HOSTKEY_PATH:/etc/grid-security/hostkey.pem -v $ONEAUTH_PATH:/var/lib/one/.one -e "ONE_XMLRPC=http://$DOCKERHOST:2633" -id $DOCKERIMAGE