#!/bin/bash
#
# https://github.com/grycap/docker-rocci-server
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
if ( ! grep "Listen\s*11443" /etc/apache2/ports.conf); then echo Listen 11443 >> /etc/apache2/ports.conf; fi
a2enmod ssl
a2enmod passenger
a2enmod mod-security
a2enmod zgridsite

sed -i "s|\[\[HOSTNAME\]\]|$(hostname)|g;s|\[\[ONE_XMLRPC\]\]|$ONE_XMLRPC|g" /etc/apache2/sites-available/occi-ssl

a2ensite occi-ssl
