#!/bin/bash
#
# https://github.com/grycap/docker-rocci-server
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
cp /etc/grid-security/hostcert.pem /etc/grid-security/certificates/
HASH=$(openssl x509 -noout -hash -in /etc/grid-security/hostcert.pem)
ln -s /etc/grid-security/certificates/hostcert.pem /etc/grid-security/certificates/${HASH}.0
